### ISSUE TITLE
Injecting app version from config.xml into config-const.js

### ISSUE THREAD

**Issue by gmarziou** [mwaylabs/generator-m-ionic#249]
Hello,

So far if I want to update my app version and use it as a constant I have to run:

~~~sh
gulp config --setWidgetAttr='version=0.0.3'
gulp build --buildVars='VERSION:0.0.3'
~~~

Maybe it would be cool to have a way to inject values from `config.xml` into `config-const.js` and so run only `gulp config`.

What do you think?

**Comment by gruppjo** [comment]
Hi @gmarziou, you mean an automatic injection of some `config.xml` infos into the `config-cost.js` to not have to run separate commands for injection in both files? 

@MathiasTim and I had a similar discussion on many occasions. While we liked the idea of having shortcuts we figured (for now) it would be easiest to have a modular approach, that may be a little more elaborate at times but would eventually allow more scenarios.

However this *is* a hot topic and we're still ping-ponging ideas, so we're open to discussions.

**Comment by gmarziou** [comment]
Yes that's what I want to do.

In fact, I'm still thinking about how to use same project to build same app with different branding (app name, icon, splash screen, css, constants) for different customers, a [white-label product](https://en.wikipedia.org/wiki/White-label_product) approach. 

I think I may need to be able to modify automaticaly config.xml and few other  key files from a kind of meta build process.

**Comment by gruppjo** [comment]
That sounds very similar to what we're doing. Have you seen this guide? https://github.com/mwaylabs/generator-m-ionic/blob/master/docs/guides/programmatically_change_configxml.md 
It explains how to use the commands: gulp config, buildVars in a continuous integration environment. In order to put splash screens there is a guide for that too: https://github.com/mwaylabs/generator-m-ionic/blob/master/docs/guides/icons_splash_screens.md

An outline of how we use it can be found in the `jenkins.sh` template - https://github.com/mwaylabs/generator-m-ionic/blob/master/generators/app/templates/jenkins.sh

**Comment by gmarziou** [comment]
Thanks a lot, these guides are very well written and they cover my needs.

**Comment by gruppjo** [comment]
Fantastic. Looks like we need to place those a little more prominently so that they can be found more easily ;)
