### ISSUE TITLE
Option to strip log statements

### ISSUE THREAD

**Issue by gmarziou** [mwaylabs/generator-m-ionic#267]
Hello

I think it could be useful to have an option to either strip out console.log() calls using [gulp-strip-debug](https://github.com/sindresorhus/gulp-strip-debug) or maybe enforces the use of $log and configure $logProvider from constants in environments.

**Comment by gmarziou** [comment]
Well I implemented the second option with $log and it works well and more angular-ish.
Maybe it could be integrated.

**Comment by gruppjo** [comment]
Hi @gmarziou, we're enforcing the absence of console.log statements with ESLint. @MathiasTim uses precommit hooks with husky to allow only console.log free code to be committed. Read more here: https://github.com/mwaylabs/generator-m-ionic/issues/231. We'll supply a guide how to do this soon.  IMHO this is cleaner way to do this, since you don't need another gulp plugin that manipulates your code. Or is there a major advantage? What do you think?

**Comment by gmarziou** [comment]
Hi @gruppjo, I agree with you about not using another gulp plugin that's why I went for the other option using $log. It has the advantage that it can differentiate between debug, warnings and errors and it lets you dynamically enable debug through $logProvider and a constant I defined in Config.ENV.

I also tend to avoid leaving debug statements in my code, but with Cordova I found they are useful to find out what's goign on before the device is ready and you can't yet put a breakpoint in chrome whime remote debugging.

Anyway, I close the issue as I think it is not a general need and I have a clean solution.

**Comment by gruppjo** [comment]
`$log` also comes in handy because when running tests with protractor angular will ignore them
