### ISSUE TITLE
File structure improvement

### ISSUE THREAD

**Issue by NicholasGlazer** [mwaylabs/generator-m-ionic#289]
According to the angular folder structure best practices: 
https://github.com/johnpapa/angular-styleguide#application-structure ,
more details here - https://scotch.io/tutorials/angularjs-best-practices-directory-structure .
For now I have some problem with gulp because of my folder structure: 

│index.html
│app.js 
├── module1 (folder)
│   ├── submodule1(folder)
│   │   ├── submodule1-ctrl.js
│   │   ├── submodule1.html
│   │   └── submodule1.scss
│   ├── module1-ctrl.js
│   ├── module1.html
│   ├── module1.scss
│   └── model.module1.js
├── assets (folder)
│   ├── fonts (folder)
│   │   ├── icons.eot
│   │   ├── icons.svg
│   │   ├── icons.ttf
│   │   └── ionicons.woff
│   └── images (folder)
│       └── yo@ 2x.png
├── components (folder)
│   ├── login.html
│   └── popover.html
├── constants (folder)
│   ├── config-const.js
│   ├── env-dev.json
│   └── env-prod.json
├── filters (folder)
│   └── filter.js
├── main.js
├── menu (folder)
│   ├── menu-ctrl.js
│   ├── menu.html
│   ├── menu-social.html
│   └── menu.scss
├── search (folder)
│   ├── search-ctrl.js
│   ├── search.html
│   ├── search.model.js
│   └── search.scss
├── settings (folder)
│   ├── settings-ctrl.js
│   ├── settings.html
│   └── settings.scss
├── starter (folder)
│   ├── starter-ctrl.js
│   ├── starter.html
│   └── starter.scss
└── styles (folder)
    └── main.scss

It will be great to choose between simple structure for smaller projects and modular scaling structure.
BTW, thank you for this great generator. Before this one, I used grunt generator wich is weak supporting, so this one much better fit for me, except few things: modular structure and angular2 and ES6(babel at least) support.

**Comment by gruppjo** [comment]
Hi @NicholasGlazer, I'm glad the generator is of value to you. Here are some thoughts:

1) File Structure: We've had lengthy discussions about project structure and modularity in the origins of this generator. E.g. https://github.com/mwaylabs/generator-m-ionic/issues/31. For now we've settled for this structure. It's easy to understand and use and serves many purposes, most important of all. Is easy to begin with but also able to scale. So unless there's an urgent and important reason we won't change the structure anymore and focus on topics with more beneficial potential. Esp. since the module structure of angular 1.x is somewhat "incomplete".

2) Angular 2 / ES6 are down the road. We'll get to it early next year I estimate. With that project structure and all will probably get an overhaul but we won't do anything drastic until we've collected enough experience.

I hope I answered all your questions :)
