### ISSUE TITLE
Cross Origin Cookie Support

### ISSUE THREAD

**Issue by zjhiphop** [mwaylabs/generator-m-ionic#396]
I just check the awsome docs about how to make the cros origin requests. 
But unfortunately, it still can not solve my problem. I have a requirement which i need send cros origin cookies for backend to check identity. 
I know browser have the policy to forbidden cros domain cookie. 
Anyway, if there is a way to solve the cross domain cookie issue, it would be very helpful.

**Comment by gruppjo** [comment]
Hi @zjhiphop. Glad you found our CORS guide helpful. I personally have no experience with CORS cookies. Maybe someone else has.
Also I recommend google searching for solutions. There might be help on stackoverflow or any of the sorts. I don't think that this is an issue we're trying to solve with this generator's dev tools.
Good luck.
Closing this, since this is more of a general issue, than one which is related to our generator.
Would be great to read your findings nonetheless!
