### ISSUE TITLE
can i set the file's indent that sub-generator create?

### ISSUE THREAD

**Issue by MinionsDave** [mwaylabs/generator-m-ionic#401]
i used to 4 indent and don't want to write unit test.
can i config the generator so that creating file using 4 indent and don't create the unit test file?

**Comment by gruppjo** [comment]
Hi @MinionsDave, in short: no.
Having an indentation of 4 would require a separate template file for every component.
I'd recommend you just leave the karma tests in there, that way you can pick up writing unit tests later and don't have to create all files again. Since they only test for the existence of the component you create they will always run and don't get in your way.
