### ISSUE TITLE
Ionic is not defined

### ISSUE THREAD

**Issue by nonsenseless** [mwaylabs/generator-m-ionic#407]
I'm testing out the app per your guides on the ionic blog--impressively put together!--and I'm trying to run 
`$ gulp --cordova "run android"
`
but I'm getting an error from gulp-eslint in user-ctrl.js that

> 'Ionic' is not defined

I changed 'Ionic' to 'ionic' and it proceeded.

**Comment by MathiasTim** [comment]
mhh I'm a bit confused.
Where did you changed the `Ionic` in the `.eslintrc` or in your code?
Did you change form upper to lower or the other way round?

Related: [#372](https://github.com/mwaylabs/generator-m-ionic/issues/372)
@gruppjo Is there anything we could/should do to make this easier?

**Comment by nonsenseless** [comment]
My apologies for being unclear. I changed user-ctrl.js from uppercase 'Ionic' to lower case 'ionic'.

I'm just getting started with Angular and Ionic so I don't know my way around very well yet, but I presume the generator was misconfigured for this file?

**Comment by gruppjo** [comment]
@nonsenseless, glad you're liking our generator. It's not a matter of misconfiguration. The libraries provided by ionic are just a little bit confusing here because they provide both `ionic` and `Ionic`. Lowercase `ionic` comes with the framework and uppercase `Ionic` with the [Ionic Platform Client](https://github.com/driftyco/ionic-platform-web-client) that you can integrate into the Generator according to the [Ionic Platform Guide](https://github.com/mwaylabs/generator-m-ionic/blob/master/docs/ecosystems/ionic_platform.md).

@MathiasTim: not sure how we could make this easier to understand?

**Comment by nonsenseless** [comment]
@gruppjo  Ahh, I think I see. I'm admittedly still unclear on why the User-Ctrl file had a reference to 'Ionic' that was triggering a linting error; is it possible to modify setup to prevent that?

Regarding clarifying it, one suggestion would be to modify the generator so that when it asks you about Integrating into the following ecosystems, you specifically note something to the effect of,

"Note that 'Ionic Platform' is a client for interacting with the Ionic Platform and is not the same as the ionic framework. If you include 'Ionic Platform' in your project, code references to 'ionic' will refer to the framework while references to 'Ionic' will refer to the platform."

**Comment by gruppjo** [comment]
I get what you mean, it's kind of explained in the Ionic Integration Guide, I think: https://github.com/mwaylabs/generator-m-ionic/blob/master/docs/ecosystems/ionic_platform.md
We do assume that if you choose the `Ionic Platform` ecosystem during setup that you know what you are doing.
