### ISSUE TITLE
Res folder splash and icons not working properly

### ISSUE THREAD

**Issue by myspivey** [mwaylabs/generator-m-ionic#455]
I tried adding splash and icons and some how have hit an issue of it not copying the resources properly. If I run `gulp --cordova "run android"` the app runs properly, however the splash and icons do not copy into the platform folder and it creates a bunch of extra folders inside the root res folder as shown below. This is off the latest copy of the generator.
![screen shot 2016-12-02 at 10 15 15 am](https://cloud.githubusercontent.com/assets/2472925/20843451/9fb2aabc-b878-11e6-8d1d-6c6256fd1bc4.png)

**Comment by myspivey** [comment]
Relevant part of config.xml

`  <platform name="android">
    <icon density="ldpi" src="res/android/current/icon-36-ldpi.png" />
    <icon density="mdpi" src="res/android/current/icon-48-mdpi.png" />
    <icon density="hdpi" src="res/android/current/icon-72-hdpi.png" />
    <icon density="xhdpi" src="res/android/current/icon-96-xhdpi.png" />
    <icon density="xxhdpi" src="res/android/current/icon-144-xxhdpi.png" />
    <icon density="xxxhdpi" src="res/android/current/icon-192-xxxhdpi.png" />
  </platform>

  <preference name="SplashMaintainAspectRatio" value="true" />
  <platform name="android">
    <splash density="land-hdpi" src="res/android/current/screen-hdpi-landscape.png" />
    <splash density="land-ldpi" src="res/android/current/screen-ldpi-landscape.png" />
    <splash density="land-mdpi" src="res/android/current/screen-mdpi-landscape.png" />
    <splash density="land-xhdpi" src="res/android/current/screen-xhdpi-landscape.png" />
    <splash density="land-xxhdpi" src="res/android/current/screen-xxhdpi-landscape.png" />
    <splash density="land-xxxhdpi" src="res/android/current/screen-xxxhdpi-landscape.png" />
  </platform>`

**Comment by gruppjo** [comment]
Hi @myspivey. This is exactly how it's supposed to work. What's the problem you're having?

**Comment by myspivey** [comment]
I guess it seems odd to create all of these extra folders outside of the ios and android folder that are specific to one platform. It greatly increases what GIT wants to pickup and add which defeats the purpose of having the default and custom folder setup. It also is building these files here, and never copying them into the build folder, it has to be done manually. I assumed that was a bug as those folders were not in .gitignore and I could not find anything to do the actual copy into the device platform desired.

**Comment by gruppjo** [comment]
Hi @myspivey, my reply is a little delayed since I've got a lot in my pipeline right now... So my reply will be brief. I hope I can still provide some clarity.

I'm still not quite sure I understand what the problem or your question is. You could give me a little more context what you're trying to achieve.

Just to be sure we're on the same page:
The purpose of the res folder is to provide different sets of icons or screens based on the `--res` build parameter. If you just want to add icons and splashscreens there's any easier setup: https://github.com/mwaylabs/generator-m-ionic/blob/master/docs/guides/icons_splash_screens.md#simple-example

To pick up some of your statements:

- They're outside the platform folders because they get completely removed if you update the platform version and since they're on gitignore you might lose your images
- it does add to git a little bit, yes
- if you correctly reference these images in the `config.xml` they correctly become part of your build, they don't need to be copied anywhere manually.
- the `res/*/current` folder is on gitignore https://github.com/mwaylabs/generator-m-ionic-demo/blob/master/.gitignore#L19

**Comment by myspivey** [comment]
I guess the issue is why are they allowed to be added to git? I can just add them to ignore but as generated files, rollback does not make sense on something that is generated at build time and treated as a dynamic file being that it can shift as to what sort of build you do run. I will close this issue and I will simply add them to the gitignore on my end.
