### ISSUE TITLE
update all deps

### ISSUE THREAD

**Issue by gruppjo** [mwaylabs/generator-m-ionic#472]
deps and devdeps for generator and generated project https://github.com/mwaylabs/generator-m-ionic-demo according to #94

**Comment by gruppjo** [comment]
bower: angular 1.6, ui-router 1x?

**Comment by MathiasTim** [comment]
angular 1.6 -> ok
ui-router -> no idea if that works. I would stick to the version the ionic guys use in their latest release
ngCordova/ionic native -> no idea if ionic native is for angular1 based projects or not.

@lordgreg any idea?

**Comment by lordgreg** [comment]
I wouldn't switch to ionic-native at all. This is pretty big change and would cause more conflict between developers. Ionic native can be used with ng1 apps, however, I'm really not sure if all of the plugins used really return promises. Not that we later found an issue with plugin because one, which we should use, returns an Observable.

**Comment by gruppjo** [comment]
Thanks for your feedback, guys. I tried angular 1.6 and I got some issues where some routes didn't load, so I suggest we stick with angular 1.5.

**Comment by MathiasTim** [comment]
yep, agree. Since Ionic is also depending of angularjs 1.5.3.
